// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "News Plattform",
//   description: "created by vijay kanwal",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from 'next'
// import { Azeret_Mono as Geist_Mono } from 'next/font/google'
import { Inter as Geist, Roboto_Mono as Geist_Mono } from "next/font/google";

import '@/app/globals.css'
import { Navbar } from '@/components/Navbar'
import { ClerkProvider } from '@clerk/nextjs'
import { ApiDataContextProvider } from './Context/Store'
import { ThemeProvider } from './Context/Theme'
const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-sans',
})
const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (

    
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased bg-gray-50 dark:bg-gray-900`}
      >
      <ClerkProvider>

        <ThemeProvider
            
          >

        <ApiDataContextProvider >

        <Navbar/>
        {children}

        </ApiDataContextProvider>
</ThemeProvider>
</ClerkProvider>
      </body>

    </html>
  
  )
}


